AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Meeca Backend Serverless Application - Staging Environment

Parameters:
  BucketName:
    Type: String
    Default: meeca2-dev
    Description: Name of the S3 bucket for storing avatars

  DynamoDBTableName:
    Type: String
    Default: MeecaApp
    Description: Name of the existing DynamoDB table

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        ENV: "staging"
        ALLOWED_HOSTS: "*"
        ALLOWED_ORIGIN: "https://www.meeca.app"
        TABLE_NAME: !Ref DynamoDBTableName
        BUCKET_NAME: !Ref BucketName
        COGNITO_USER_POOL_ID: "us-west-1_OhDnHEXLi"
        COGNITO_USER_POOL_CLIENT_ID: "6cgbaguv56185c18o0q7khb9c8"
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'https://www.meeca.app'"
    BinaryMediaTypes:
      - multipart/form-data
      - image/jpeg
      - image/png
      - image/gif

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  # Basic CRUD operations
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  # Batch operations
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  # Condition check operations
                  - dynamodb:ConditionCheckItem
                  # Describe and list operations for development/debugging
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTables
                  # Transaction operations
                  - dynamodb:TransactGetItems
                  - dynamodb:TransactWriteItems
                Resource:
                  # Main table
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}
                  # All indexes
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}/index/*
                  # Specific indexes if you want to be more restrictive
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}/index/GSI1PK-GSI1SK-index
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}/index/GSI2PK-GSI2SK-index
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}/index/OwnerId-index
              # Optional: Add CloudWatch monitoring permissions
              # - Effect: Allow
              #   Action:
              #     - cloudwatch:PutMetricData
              #   Resource: "*"
              #   Condition:
              #     StringEquals:
              #       cloudwatch:namespace: "MeecaApp/DynamoDB"

        # You might also want to add auto-scaling permissions if you plan to use it
        # - PolicyName: DynamoDBAutoScaling
        #   PolicyDocument:
        #     Version: "2012-10-17"
        #     Statement:
        #       - Effect: Allow
        #         Action:
        #           - application-autoscaling:RegisterScalableTarget
        #           - application-autoscaling:DescribeScalableTargets
        #           - application-autoscaling:PutScalingPolicy
        #           - application-autoscaling:DescribeScalingPolicies
        #         Resource:
        #           - !Sub arn:aws:application-autoscaling:${AWS::Region}:${AWS::AccountId}:scalable-target/*
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: !Sub arn:aws:s3:::${BucketName}/*

  MeecaApiNew:
    Type: AWS::Serverless::Api
    Properties:
      StageName: StagingEnv
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'https://www.meeca.app'"
      Auth:
        DefaultAuthorizer: BaseUserRequestAuth
        Authorizers:
          BaseUserRequestAuth:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt BaseUserRequestFunction.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
          AdminUserRequestAuth:
            FunctionPayloadType: REQUEST
            FunctionArn: !GetAtt AdminUserRequestFunction.Arn
            Identity:
              Headers:
                - Authorization
              ReauthorizeEvery: 0
        AddDefaultAuthorizerToCorsPreflight: False
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref MeecaApiNew
      StageName: StagingEnv

  # Authorizer functions
  BaseUserRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/permissions/
      Handler: api.base_user.base_user_handler
      Runtime: python3.9
      Policies:
        - AWSLambdaBasicExecutionRole

  AdminUserRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/permissions/
      Handler: api.admin_user.admin_user_handler
      Runtime: python3.9
      Policies:
        - AWSLambdaBasicExecutionRole

  # Avatar functions
  AvatarsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/avatars/
      Handler: handler.avatar_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        AvatarsPost:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /avatars/create
            Method: POST
            Auth:
              Authorizer: AdminUserRequestAuth
        AvatarsGet:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /avatars
            Method: GET
            Auth:
              Authorizer: BaseUserRequestAuth
        AvatarsGetAll:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /avatars/all
            Method: GET
            Auth:
              Authorizer: AdminUserRequestAuth
        AvatarsVoicesGet:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /avatars/voices
            Method: GET
            Auth:
              Authorizer: AdminUserRequestAuth
        AvatarsVoicesPost:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /avatars/voices/create
            Method: POST
            Auth:
              Authorizer: AdminUserRequestAuth

  # User profile functions
  UserProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/userprofile/
      Handler: handler.user_profile_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        UserProfileGet:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /user-profile
            Method: GET
        UserProfilePost:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /user-profile
            Method: POST

  # Room functions
  RoomsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/rooms/
      Handler: handler.room_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        RoomMessagesGet:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            # TODO, should use path <id> param rather than ?id=
            Path: /rooms/{room_id}
            Method: GET
        RoomsPost:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /rooms
            Method: POST
        RoomMessagesPost:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /rooms/{room_id}/messages
            Method: POST
        RoomMessagesGenerateAudio:
          Type: Api
          Properties:
            RestApiId: !Ref MeecaApiNew
            Path: /rooms/messages/{message_id}/audio
            Method: POST

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
